"""
Export per-operator performance artifacts from an address_remapping graph.

Recommended usage:

    cd H:\\dev\\projects\\ndp-sim\\address_remapping
    $env:PYTHONPATH='src'
    python scripts\\export_op_performance_summary.py ^
      examples\\graphs\\transformer_layer_single_slice.json ^
      --config examples\\configs\\performance_config.json ^
      --mode remap

Files generated by the command above:

    outputs\\performance\\transformer_layer_single_slice\\
      transformer_layer_single_slice_op_summary_remap.json
      transformer_layer_single_slice_roofline_remap.json
      transformer_layer_single_slice_roofline_remap_util_compact_sorted.csv
"""

import argparse
import csv
import json
from pathlib import Path
from typing import Dict, List, Mapping, Sequence

from address_remapping.graph import load_graph_file
from address_remapping.performance import analyze_graph_performance, load_performance_config
from address_remapping.roofline import build_roofline_summary


def _build_rows(payload: Mapping[str, object], mode: str) -> List[Dict[str, object]]:
    modes = payload.get("modes", {})
    if mode not in modes:
        raise ValueError(f"Unknown mode '{mode}'. Available modes: {', '.join(sorted(modes))}")

    rows: List[Dict[str, object]] = []
    op_breakdown = modes[mode]["op_breakdown"]
    for index, op in enumerate(op_breakdown):
        analytical = op.get("analytical_model", {})
        roofline = op.get("true_roofline", {})
        rows.append(
            {
                "index": index,
                "stage_name": op.get("stage_name"),
                "kind": op.get("kind"),
                "op_name": op.get("op_name"),
                "op_type": op.get("op_type"),
                "latency_cycles": op.get("latency_cycles"),
                "hardware_measured_cycles": op.get("hardware_measured_cycles"),
                "speedup_vs_baseline": modes[mode].get("speedup_vs_baseline"),
                "bytes_read": op.get("bytes_read"),
                "bytes_written": op.get("bytes_written"),
                "total_bytes": op.get("total_bytes"),
                "work_ops": op.get("work_ops"),
                "arithmetic_intensity": op.get("arithmetic_intensity"),
                "roofline_cycles": roofline.get("roofline_cycles"),
                "roofline_compute_bound_cycles": roofline.get("compute_bound_cycles"),
                "roofline_bandwidth_bound_cycles": roofline.get("bandwidth_bound_cycles"),
                "estimated_latency_cycles": analytical.get("estimated_latency_cycles"),
                "lower_bound_cycles": analytical.get("lower_bound_cycles"),
                "compute_bound_cycles": analytical.get("compute_bound_cycles"),
                "memory_access_bound_cycles": analytical.get("memory_access_bound_cycles"),
                "ag_issue_bound_cycles": analytical.get("ag_issue_bound_cycles"),
                "ring_transfer_bound_cycles": analytical.get("ring_transfer_bound_cycles"),
                "latency_to_lower_bound_ratio": analytical.get("latency_to_lower_bound_ratio"),
            }
        )
    return rows


def _fmt_percent_number(value: object) -> object:
    if value is None:
        return None
    return f"{float(value) * 100.0:.2f}"


def _simulator_error_percent(latency_cycles: object, hardware_measured_cycles: object) -> object:
    if latency_cycles is None or hardware_measured_cycles is None:
        return None
    measured = float(hardware_measured_cycles)
    if measured == 0.0:
        return None
    simulated = float(latency_cycles)
    return f"{((simulated - measured) / measured) * 100.0:.2f}"


def _build_final_roofline_rows(summary: Mapping[str, object], sort_by_latency_share: bool = True) -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    for index, op in enumerate(summary.get("operators", [])):
        rows.append(
            {
                "index": index,
                "op_name": op.get("op_name"),
                "op_type": op.get("op_type"),
                "latency_share_of_total(%)": _fmt_percent_number(op.get("latency_share_of_total")),
                "latency_cycles": op.get("latency_cycles"),
                "hardware_measured_cycles": op.get("hardware_measured_cycles"),
                "simulator_error_vs_measured(%)": _simulator_error_percent(
                    op.get("latency_cycles"),
                    op.get("hardware_measured_cycles"),
                ),
                "roofline_compute_utilization(%)": _fmt_percent_number(op.get("roofline_compute_utilization")),
                "analytical_compute_utilization(%)": _fmt_percent_number(op.get("analytical_efficiency")),
                "measured_compute_utilization(%)": _fmt_percent_number(op.get("measured_efficiency")),
                "roofline_bandwidth_utilization(%)": _fmt_percent_number(op.get("roofline_bandwidth_utilization")),
                "analytical_bandwidth_utilization(%)": _fmt_percent_number(
                    op.get("analytical_bandwidth_utilization")
                ),
                "measured_bandwidth_utilization(%)": _fmt_percent_number(
                    op.get("measured_bandwidth_utilization")
                ),
                "work_ops": op.get("work_ops"),
                "total_bytes": op.get("total_bytes"),
                "arithmetic_intensity_ops_per_byte": op.get("arithmetic_intensity_ops_per_byte"),
            }
        )

    if sort_by_latency_share:
        rows.sort(
            key=lambda row: float(row["latency_share_of_total(%)"])
            if row.get("latency_share_of_total(%)") not in (None, "")
            else float("-inf"),
            reverse=True,
        )
    return rows


def _write_rows_to_csv(rows: Sequence[Mapping[str, object]], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()) if rows else [])
        if rows:
            writer.writeheader()
            writer.writerows(rows)


def _default_output_stem(input_path: str, mode: str) -> Path:
    source = Path(input_path)
    return Path("outputs") / "performance" / source.stem / f"{source.stem}_op_summary_{mode}"


def _default_roofline_output_paths(input_path: str, mode: str) -> tuple[Path, Path]:
    source = Path(input_path)
    base_dir = Path("outputs") / "performance" / source.stem
    return (
        base_dir / f"{source.stem}_roofline_{mode}.json",
        base_dir / f"{source.stem}_roofline_{mode}_util_compact_sorted.csv",
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Export one-row-per-op performance summary and final roofline CSV.",
        epilog=(
            "Example:\n"
            "  cd H:\\dev\\projects\\ndp-sim\\address_remapping\n"
            "  $env:PYTHONPATH='src'\n"
            "  python scripts\\export_op_performance_summary.py "
            "examples\\graphs\\transformer_layer_single_slice.json "
            "--config examples\\configs\\performance_config.json "
            "--mode remap\n\n"
            "Outputs:\n"
            "  outputs\\performance\\<graph>\\<graph>_op_summary_<mode>.json\n"
            "  outputs\\performance\\<graph>\\<graph>_roofline_<mode>.json\n"
            "  outputs\\performance\\<graph>\\<graph>_roofline_<mode>_util_compact_sorted.csv"
        ),
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument("path", help="Input graph path. Supports internal graph JSON and external execplan JSON.")
    parser.add_argument("--config", help="Performance config path.", default=None)
    parser.add_argument("--mode", choices=["baseline", "remap", "remap_interleave"], default="remap")
    parser.add_argument(
        "--output-stem",
        help="Output path without extension. Defaults under outputs/performance/<graph>/.",
        default=None,
    )
    parser.add_argument(
        "--roofline-json",
        help="Path for roofline summary JSON. Defaults under outputs/performance/<graph>/.",
        default=None,
    )
    parser.add_argument(
        "--roofline-csv",
        help="Path for final compact roofline CSV. Defaults under outputs/performance/<graph>/.",
        default=None,
    )
    args = parser.parse_args()

    hardware, perf_cfg = load_performance_config(args.config)
    graph_spec = load_graph_file(args.path)
    payload = analyze_graph_performance(graph_spec, hardware, perf_cfg, include_request_traces=False)
    rows = _build_rows(payload, args.mode)
    roofline_summary = build_roofline_summary(payload, mode=args.mode, graph_name=Path(args.path).stem)
    roofline_rows = _build_final_roofline_rows(roofline_summary, sort_by_latency_share=True)

    output_stem = Path(args.output_stem) if args.output_stem else _default_output_stem(args.path, args.mode)
    output_stem.parent.mkdir(parents=True, exist_ok=True)
    default_roofline_json, default_roofline_csv = _default_roofline_output_paths(args.path, args.mode)

    json_path = output_stem.with_suffix(".json")
    roofline_json_path = Path(args.roofline_json) if args.roofline_json else default_roofline_json
    roofline_csv_path = Path(args.roofline_csv) if args.roofline_csv else default_roofline_csv

    json_path.write_text(json.dumps(rows, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    roofline_json_path.parent.mkdir(parents=True, exist_ok=True)
    roofline_json_path.write_text(json.dumps(roofline_summary, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    _write_rows_to_csv(roofline_rows, roofline_csv_path)

    print(
        json.dumps(
            {
                "mode": args.mode,
                "row_count": len(rows),
                "json": str(json_path),
                "roofline_json": str(roofline_json_path),
                "roofline_csv": str(roofline_csv_path),
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
